import { StyleSheet} from 'react-native';
import {globalHeightMargin, globalWidthMargin, hp, wp} from './utils';

export const fonts = {
  bold: 'YekanBakh-Bold',
  regular: 'YekanBakh-Regular',
  medium: 'YekanBakh-Medium',
  light: 'YekanBakh-Light',
};

export default StyleSheet.create({
  container: {
    width: wp(88),
    marginTop: hp(5),
    alignItems: 'center',
  },
  headerWrapper: {
    alignItems: 'center',
    flexDirection: 'row',
    alignSelf: 'center',
    width: '97%',
    justifyContent: 'space-between',
  },
  currentDateButton: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    width: wp(30),
  },
  monthLabel: {
    color: '#000',
    textAlign: 'center',
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  labelControl: {
    color: '#0087E0',
    fontFamily: fonts.regular,
    fontSize: 16,
  },
  buttonControl: {
    alignItems: 'center',
    width: '30%',
  },
  dayLabelsWrapper: {
    flexDirection: 'row-reverse',
    alignSelf: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: hp(2),
  },
  dayLabels: {
    color: '#8F97B2',
    textAlign: 'center',
    width: globalWidthMargin * 8,
    height: globalWidthMargin * 8,
    textAlignVertical: 'center',
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  weekRow: {
    flexDirection: 'row-reverse',
  },

  dayButton: {
    borderRadius: wp(1),
    alignSelf: 'center',
    justifyContent: 'center',
  },
  selectedToday: {
    alignSelf: 'center',
    justifyContent: 'center',
    width: globalWidthMargin * 8,
    height: globalWidthMargin * 8,
    borderRadius: globalWidthMargin * 2,
  },
  selectedDayLabel: {
    color: '#000000',
  },
  selectedDatePicker: {
    width: globalWidthMargin * 8,
    height: globalWidthMargin * 8,
    borderRadius: globalWidthMargin * 2,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  selectedDatePickerDayLabel: {
    color: 'white',
  },
  selectedDayBackground: {
    backgroundColor: '#62CCF5',
  },
  startDayWrapper: {
    width: globalWidthMargin * 8,
    height: globalWidthMargin * 8,
    backgroundColor: '#62CCF5',
    alignSelf: 'center',
    justifyContent: 'center',
    borderTopRightRadius: globalWidthMargin * 2,
    borderBottomRightRadius: globalWidthMargin * 2,
  },
  startAndEndLabel: {
    color: 'white',
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  endDayWrapper: {
    width: globalWidthMargin * 8,
    height: globalWidthMargin * 8,
    borderTopLeftRadius: globalWidthMargin * 2,
    borderBottomLeftRadius: globalWidthMargin * 2,
    backgroundColor: '#62CCF5',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  inRangeDay: {
    width: globalWidthMargin * 8,
    height: globalWidthMargin * 8,
    backgroundColor: '#E8F3FC',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  dayWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: globalWidthMargin * 13.2,
    height: globalWidthMargin * 13.2,
  },
  daysWrapper: {
    alignSelf: 'center',
    justifyContent: 'center',
  },
  dayLabel: {
    color: '#000',
    alignSelf: 'center',
    fontFamily: fonts.light,
    fontSize: 16,
  },
  disabledText: {
    fontSize: 14,
    color: '#BBBBBB',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  selector: {
    backgroundColor: 'white',
    width: wp(100),
    alignSelf: 'center',
    alignItems: 'center',
    height: hp(100),
    justifyContent: 'space-between',
  },
  selectorRow: {
    paddingTop: globalHeightMargin * 4,
    paddingBottom: globalHeightMargin * 2,
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: wp(90),
  },
  selectorLabel: {
    color: '#8F97B2',
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  listContainer: {
    zIndex: 10000,
    width: wp(90),
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#F7F8FA',
    borderTopRightRadius: globalWidthMargin * 2,
    borderBottomRightRadius: globalWidthMargin * 2,
    borderTopLeftRadius: globalWidthMargin * 2,
    borderBottomLeftRadius: globalWidthMargin * 2,
  },
  yearItem: {
    width: '42%',
    paddingVertical: globalHeightMargin * 3,
    marginTop: hp(2),
    borderRadius: globalWidthMargin * 2,
    justifyContent: 'center',
  },
  yearSelectorScrollViewContainer: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    paddingBottom: hp(4),
    justifyContent: 'center',
  },
  yearSelectorScrollView: {
    backgroundColor: '#F7F8FA',
    minHeight: hp(50),
    maxHeight: hp(72),
    borderTopRightRadius: globalWidthMargin * 2,
    borderBottomRightRadius: globalWidthMargin * 2,
    borderTopLeftRadius: globalWidthMargin * 2,
    borderBottomLeftRadius: globalWidthMargin * 2,
  },
  yearLabel: {
    textAlign: 'center',
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  yearGradint: {
    position: 'absolute',
    width: '50%',
    bottom: -1,
    left: 0,
    height: hp(8),
    zIndex: 10000000,
    borderBottomLeftRadius: globalWidthMargin,
  },
  selectorDevider: {
    width: 1,
    height: '85%',
    backgroundColor: '#14151A0D',
    alignSelf: 'center',
  },
  selectorButtonContainer: {
    borderTopColor: '#14151A1A',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: globalHeightMargin * 4,
    borderTopWidth: 1,
    width: '100%',
  },
  selectorButton: {
    width: wp(88),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#21D5B0',
    height: hp(11),
    borderRadius: globalWidthMargin * 2,
  },
  selectorButtonText: {
    color: 'white',
    fontSize: 17,
    fontFamily: fonts.bold,
  },
  chevronDown: {
    width: globalWidthMargin * 4,
    height: globalWidthMargin * 4,
    marginRight: globalWidthMargin,
  },
  chevronLeft: {
    width: globalWidthMargin * 4,
    height: globalWidthMargin * 4,
    transform: [{rotate: '90deg'}],
  },
  selectedSameDay: {
    backgroundColor: '#14151A0D',
    alignSelf: 'center',
    justifyContent: 'center',
    width: globalWidthMargin * 8,
    height: globalWidthMargin * 8,
    borderRadius: globalWidthMargin * 2,
    color: 'white',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: fonts.bold,
  },
});
